name: test_project
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  either_dart: ^1.0.0
  json_annotation: ^4.7.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dio: ^5.2.1+1
  get_it: ^7.6.0
  flutter_svg: ^2.0.2
  shared_preferences: ^2.2.0
  formz: ^0.6.0
  cupertino_icons: ^1.0.2
  awesome_snackbar_content: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.4
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
